### ISSUE TITLE
iTerm Colorscheme

### ISSUE THREAD

**Issue by bpinto** [mkarmona/colorsbox#2]
Hi, do you have a colorscheme for iTerm?

I am using the colorscheme-material theme.

Thanks for the great colors!

**Comment by mkarmona** [comment]
Hi @bpinto , You're very welcome!.
sorry but I haven't. I couldn't create a colour scheme for iTerm because I'm a Linux user.

**Comment by bpinto** [comment]
Hum... do you know if there is a tool that convert from one terminal to another? Which terminal do you have the colors configured to?

**Comment by mkarmona** [comment]
well, regarding terminals, I'm using urxvt. But those colour schemes are
for GVim only so my colour terminal choice is gruvbox
<https://github.com/morhetz/gruvbox-contrib/blob/master/urxvt256/gruvbox-urxvt256.xresources>
.
Sorry but I don't know any converter from xresources/xdefaults to iterm2.



​
Saludos,
Miguel Carmona
PGP PUBLIC KEY ID 53CC0DA1DED522FD
<https://pgp.mit.edu/pks/lookup?op=get&search=0x53CC0DA1DED522FD>

**Comment by mkarmona** [comment]
well, regarding terminals, I'm using urxvt. But those colour schemes are for GVim only so my colour terminal choice is [gruvbox](https://github.com/morhetz/gruvbox-contrib/blob/master/urxvt256/gruvbox-urxvt256.xresources). Sorry but I don't know any converter from xresources/xdefaults to iterm2.

**Comment by bpinto** [comment]
Perhaps http://terminal.sexy?

**Comment by mkarmona** [comment]
Cool!
